### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by zmj1316** [Tianji95/densepose-caffe2-compile-error#1]
发行版自带 Python 的不建议用 pip 去装这些常见的库， 因为这些库用 apt 都能直接装，因为apt是发行版对应的，一般不会出问题，pip就不一定了，尤其是涉及到二进制库的这些；

顺便一提，这个不如写到 github page 上面当blog吧....

**Comment by Tianji95** [comment]
说的很对＠_＠caffe2官网error page有一个建议也是这样的，我一开始没看到，后来才知道这回事。其实如果自己装一个Python，然后把pip和Python路径设置好就会少踩很多坑了
至于github page，我一直想自己买vps搭一个博客所以就先懒得用，而自己的博客一直咸鱼这没做。。先这样挂着吧，反正没人看我就自己放着防止以后自己用
